# -*- coding: utf-8 -*-
"""SkinCare_AI_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGdpRSFPZpVMmE3-Z-OYOBhnRQ7TiXJo
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

TRAIN_DIR = "Skin-types2-1/train"
VAL_DIR   = "Skin-types2-1/valid"
IMG_SIZE  = (224, 224)
BATCH     = 32

# Strong augmentation to prevent overfitting → better generalisation
train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    zoom_range=0.25,
    horizontal_flip=True,
    vertical_flip=False,
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.1,
    brightness_range=[0.75, 1.25],   # simulate different lighting
    channel_shift_range=20.0,        # simulate different skin tones
    fill_mode="nearest",
)
val_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    TRAIN_DIR, target_size=IMG_SIZE, batch_size=BATCH,
    class_mode="categorical", shuffle=True, seed=42
)
val_data = val_gen.flow_from_directory(
    VAL_DIR, target_size=IMG_SIZE, batch_size=BATCH,
    class_mode="categorical", shuffle=False
)

CLASS_NAMES = list(train_data.class_indices.keys())
NUM_CLASSES = len(CLASS_NAMES)
print("Classes:", CLASS_NAMES)
print("Train samples:", train_data.samples)
print("Val   samples:", val_data.samples)

"""## 4️⃣  Build Model — EfficientNetB0 (More Accurate Than MobileNetV2)"""

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import (Dense, GlobalAveragePooling2D, Dropout, BatchNormalization)
from tensorflow.keras.models import Model
from tensorflow.keras import regularizers

# EfficientNetB0 — better accuracy/size trade-off than MobileNetV2
base = EfficientNetB0(weights="imagenet", include_top=False,
                       input_shape=(224, 224, 3))
base.trainable = False  # Phase 1: backbone frozen

x = base.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(256, activation="relu",
           kernel_regularizer=regularizers.l2(1e-3))(x)
x = Dropout(0.5)(x)
x = Dense(128, activation="relu",
           kernel_regularizer=regularizers.l2(1e-3))(x)
x = Dropout(0.5)(x)
out = Dense(NUM_CLASSES, activation="softmax")(x)

model = Model(inputs=base.input, outputs=out)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("Phase 1 trainable params:",
      sum([tf.size(w).numpy() for w in model.trainable_weights]))
model.summary(line_length=80)

"""## 5️⃣  Phase 1 — Train Head Only (Frozen Backbone)"""

from tensorflow.keras.callbacks import (EarlyStopping, ReduceLROnPlateau,
                                           ModelCheckpoint)

cb_phase1 = [
    EarlyStopping(monitor="val_accuracy", patience=5,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                      patience=3, min_lr=1e-6, verbose=1),
    ModelCheckpoint("best_phase1.h5", monitor="val_accuracy",
                    save_best_only=True, verbose=1),
]

history1 = model.fit(
    train_data, validation_data=val_data,
    epochs=10, callbacks=cb_phase1
)

print(f"\n✅  Phase 1 best val_accuracy: "
      f"{max(history1.history['val_accuracy']):.4f}")

"""## 6️⃣  Phase 2 — Fine-Tune Top Layers (Key for Stability!)"""

# Unfreeze the top 30 layers of EfficientNetB0 for fine-tuning
for layer in base.layers[-10:]:
    if not isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = True

# Much lower LR to avoid destroying pretrained weights
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

cb_phase2 = [
    EarlyStopping(monitor="val_accuracy", patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor="val_loss", factor=0.3,
                      patience=3, min_lr=1e-7, verbose=1),
    ModelCheckpoint("skin_model.h5", monitor="val_accuracy",
                    save_best_only=True, verbose=1),
]

history2 = model.fit(
    train_data, validation_data=val_data,
    epochs=30, callbacks=cb_phase2
)

print(f"\n✅  Phase 2 best val_accuracy: "
      f"{max(history2.history['val_accuracy']):.4f}")
print("✅  Best model saved → skin_model.h5")

